### ISSUE TITLE
This repo should have a license

### ISSUE THREAD

**Issue by tekknolagi** [tekknolagi/isdt#5]
MIT?

**Comment by tchebb** [comment]
Is MIT good for non-code repos? This type of thing seems like it should be Creative Commons or something.

**Comment by tchebb** [comment]
CC-BY or CC0, perhaps?

**Comment by tekknolagi** [comment]
I'd be more interested in CC BY-SA but CC BY could be good too

**Comment by tekknolagi** [comment]
We could defer this a little by leaving a comment to the tune of "all rights reserved - please contact us if you would like to use this content"

**Comment by tekknolagi** [comment]
Discussed offline; CC BY-SA it is
