### ISSUE TITLE
Add meeting times and other administrivia

### ISSUE THREAD

**Issue by tekknolagi** [tekknolagi/isdt#6]
We know a lot more of this now that we have a course in SIS

**Comment by tekknolagi** [comment]
Added Piazza in 4566ab19a5f9f4b911a36edd7cc82c9d58d72a0f

**Comment by tchebb** [comment]
We should be a bit more specific about grading. "Students will be evaluated 100% on homework assignments" is all we have now, but we don't have any kind of rubric, or even say how many assignments there'll be and whether they all contribute equally to the final grade.

**Comment by tekknolagi** [comment]
Discussed offline; I think it's fine being ambiguous for now.

**Comment by tekknolagi** [comment]
I think this is done now after 22de2a7c296dd8939a6b6a0bb92eace572ad75b4 and dc1da3d18b1408ea4b36e894cf40665b665f7fe2
